---
version: 1
applications:
- name: APPLICATION_NAME
  type: web
  path: ../
  memory: 2048M
  disk_quota: 2048M
  instances: 1
  health-check-type: process
  timeout: 180
  stack: cflinuxfs3
  buildpacks:
  - https://github.com/cloudfoundry/python-buildpack#develop
  env:
    ACCEPT_EULA: Y
